#!/usr/bin/env php
<?php
/**
 * Shell script for generate a bare CodeIgniter migration file
 *
 * @author      Sithu K. <cithukyaw@gmail.com>
 * @license     http://www.opensource.org/licenses/mit-license.php MIT License
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE
 */

require 'src/BareMigration.php';

new BareMigration();
